### Starting with PyTorch

Let's start by importing PyTorch

In [1]:
import torch
torch.__version__

'2.5.1+cu124'

In [2]:
scalar = torch.tensor(5)
scalar.ndim

0

In [3]:
scalar.item()

5

In [4]:
scalar.shape

torch.Size([])

Dimensions are basically likes axes in which data is arranged.

In [5]:
vector = torch.tensor([7,7])
print(vector.ndim)
vector.shape

1


torch.Size([2])

In [6]:
MATRIX = torch.tensor([[1,4],
                       [2,6]])
print(MATRIX.ndim)
MATRIX.shape

2


torch.Size([2, 2])

In [7]:
TENSOR = torch.tensor([[[1,2,3],
                        [1,3,8],
                        [4,6,9]]])
print(TENSOR.ndim)
TENSOR.shape

3


torch.Size([1, 3, 3])

In common practice, scalars and vectors are denoted by small letters whereas matrices and tensors by capital letters.

In [8]:
random_tensor = torch.rand(size=(3,4))
random_tensor, random_tensor.dtype

(tensor([[0.2510, 0.1812, 0.8576, 0.6969],
         [0.6004, 0.1744, 0.5651, 0.5859],
         [0.4694, 0.2872, 0.7070, 0.3432]]),
 torch.float32)

In [9]:
random_image_tensor = torch.rand(size=(224,224,3))

In [10]:
matrix_with_zeros = torch.zeros(size=(3,4))
matrix_with_ones = torch.ones(size=(3,4))

In [56]:
torch.full((2,4),1)

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1]])

In [11]:
zero_to_ten = torch.arange(0,10,1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
matrix_like_last = torch.zeros_like(input=zero_to_ten)

The most common datatype used in PyTorch is `torch.float` or `torch.float32` but we have access to some other datatypes as well like `torch.float16`, `torch.float64`. It all has to do with precision and amount of data that is being used to store them

In [13]:
some_tensor = torch.rand(size=(3,4))

print(some_tensor.device,some_tensor.dtype)

cpu torch.float32


In [14]:
some_tensor.size()

torch.Size([3, 4])

In [15]:
some_tensor.shape

torch.Size([3, 4])

Tensors dont change unless they're re-assigned

In [16]:
TENSOR +10

tensor([[[11, 12, 13],
         [11, 13, 18],
         [14, 16, 19]]])

In [17]:
TENSOR

tensor([[[1, 2, 3],
         [1, 3, 8],
         [4, 6, 9]]])

In [18]:
torch.mul(TENSOR,TENSOR)

tensor([[[ 1,  4,  9],
         [ 1,  9, 64],
         [16, 36, 81]]])

In [19]:
torch.tensor([1,2,3])@torch.tensor([[1],[2],[3]])

tensor([14])

In [20]:
torch.manual_seed(42)
tensor_A = torch.tensor([[1, 2, 3],
                         [3, 4, 3]], dtype=torch.float32)

linear = torch.nn.Linear(in_features=2,
                         out_features=12)

x = tensor_A.T
out = linear(x)

print(f"Input shape: {x.shape}\n")

print(f"Output:{out}\n Output shape: {out.shape}")

Input shape: torch.Size([3, 2])

Output:tensor([[ 1.7432,  1.4570,  0.0735,  0.4764, -0.8662,  0.3132,  1.4483, -0.5592,
          1.4046,  0.3283, -0.8042,  1.5570],
        [ 2.8707,  1.9409,  0.0612,  0.5474, -0.7616,  1.0602,  2.0665, -0.3181,
          2.0542,  0.1784, -1.2129,  1.7389],
        [ 2.8244,  1.1257, -0.2364, -0.2121,  0.3805,  1.5425,  2.4931,  0.1227,
          2.4948, -0.3319, -1.4557,  0.9826]], grad_fn=<AddmmBackward0>)
 Output shape: torch.Size([3, 12])


In [21]:
x = torch.arange(0,100,10)

print(f"min, max and mean of x is {x.min()}, {x.max()} and {x.type(torch.float32).mean()}")

min, max and mean of x is 0, 90 and 45.0


In [59]:
print(f"Position of maximum value is {x.argmax()}")
print(f"Position of minimum value is {x.argmin()}")
print(f"Sorted indices are {x.argsort()}")

Position of maximum value is 9
Position of minimum value is 0
Sorted indices are tensor([[[0, 1, 2, 3, 4]],

        [[0, 1, 2, 3, 4]]])


In [23]:
x.type(torch.float32)

tensor([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.])

In [24]:
x = x.reshape((2,1,5))

In [49]:
x.mT.shape

torch.Size([2, 5, 1])

In [26]:
torch.stack((x,x),dim=1)

tensor([[[[ 0, 10, 20, 30, 40]],

         [[ 0, 10, 20, 30, 40]]],


        [[[50, 60, 70, 80, 90]],

         [[50, 60, 70, 80, 90]]]])

In [27]:
torch.stack((x,x),dim=2)

tensor([[[[ 0, 10, 20, 30, 40],
          [ 0, 10, 20, 30, 40]]],


        [[[50, 60, 70, 80, 90],
          [50, 60, 70, 80, 90]]]])

In [28]:
torch.squeeze(x)

tensor([[ 0, 10, 20, 30, 40],
        [50, 60, 70, 80, 90]])

In [29]:
torch.unsqueeze(x,dim=0).shape

torch.Size([1, 2, 1, 5])

Changing the view also changes the original tensor

In [30]:
z = torch.permute(x,dims=(1,2,0))

In [31]:
z[0][0][1]= 2

In [32]:
x

tensor([[[ 0, 10, 20, 30, 40]],

        [[ 2, 60, 70, 80, 90]]])

In [33]:
x[0][0][0]

tensor(0)

In [34]:
x[:,0,0]

tensor([0, 2])

In [35]:
x[:,:,0]

tensor([[0],
        [2]])

In [36]:
import numpy as np

arr = np.arange(1.,8.)
arr_pyt = torch.arange(1.,9.)
arr_to_pyt = torch.from_numpy(arr).type(torch.float32)

In [37]:
arr_pyt.dtype

torch.float32

In [38]:
arr_np = arr_pyt.numpy()
arr_np

array([1., 2., 3., 4., 5., 6., 7., 8.], dtype=float32)

In [39]:
import torch
torch.cuda.is_available()

True

In [40]:
torch.cuda.device_count()

1

In [41]:
%%time
a = torch.randn(size=(900,900),device='cuda')

a@a

CPU times: user 40.9 ms, sys: 106 ms, total: 146 ms
Wall time: 156 ms


tensor([[ 12.5167,  13.3376,  -1.7518,  ...,  36.1855, -13.4834,  13.0763],
        [ 37.3518, -71.7717,  20.6837,  ...,  28.9629,  -1.4702,  42.1063],
        [ -4.2681,  20.5782,  14.7125,  ...,  -1.0531, -16.2364,   8.8372],
        ...,
        [  7.8831, -73.6643,  15.6990,  ...,  34.4776, -16.2214,  18.9923],
        [ 12.5832, -32.5659,  50.3085,  ..., -19.9516,  38.0608,  -1.9526],
        [-17.9125, -14.7391,   5.6665,  ...,   8.9514,  -3.9312,   2.8804]],
       device='cuda:0')

In [42]:
%%time
a = torch.randn(size=(100,100))


a@a


CPU times: user 14.7 ms, sys: 631 μs, total: 15.3 ms
Wall time: 2.47 ms


tensor([[ 5.3780e+00,  1.4454e+00, -5.5501e-01,  ...,  1.7749e+00,
          4.8520e+00, -8.6914e+00],
        [ 8.8227e+00, -1.2582e+00,  1.2720e+01,  ...,  9.9873e+00,
          6.3458e+00, -9.4163e+00],
        [ 1.4768e+01, -4.8680e+00, -1.0525e+00,  ...,  1.7069e+01,
          1.1970e+00, -3.3115e+00],
        ...,
        [ 1.4531e+01, -1.1605e+01, -1.2939e+01,  ..., -1.2411e-02,
         -1.7874e+01, -9.2436e-01],
        [-2.4831e+00, -9.7061e+00, -2.4210e+01,  ...,  5.4425e+00,
          1.0349e+01,  1.8240e+01],
        [-4.4259e+00,  3.9231e+00, -2.4829e+01,  ..., -1.0627e+01,
          7.1707e+00,  1.6531e+00]])